[package]
name = "RustySpine"
version = "0.1.0"
authors = ["Aloento <Aloento@Q-Audio.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.8.0", features = ["macros"] }
object-pool = "0.5.3"
