pub mod atlas_attachment_loader;
pub mod attachment_loader;
pub mod bounding_box_attachment;
pub mod clipping_attachment;
pub mod mesh_attachment;
pub mod path_attachment;
pub mod point_attachment;
pub mod region_attachment;
pub mod attachment;
